### ISSUE TITLE
[DEFECT] Meta object becomes nested

### ISSUE THREAD

**Issue by dhill2522** [idaholab/HERON#32]
--------
Defect Description
--------

**Describe the defect**

When using a transfer function in a component, the `meta` object becomes nested with call the the evaluate method.

##### What did you expect to see happen?

The meta object should be updated, but not become nested when a component transfer function is evaluated.

##### What did you see instead?

The meta object nested once for each iteration causing a crash later on.

##### Do you have a suggested fix for the development team?

I have a fix with a unit test addressing this is a PR.

**Describe how to Reproduce**
1. Write a custom dispatcher that evaluates a dispatch using a user-provided transfer function.

**Screenshots and Input Files**
Please attach the input file(s) that generate this error.  The simpler the input, the faster we can find the issue.

**Platform (please complete the following information):**
 - OS: Fedora
 - Version: 32
 - Dependencies Installation: CONDA

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [ ] 1. Is it tagged with a type: defect or task?
- [ ] 2. Is it tagged with a priority: critical, normal or minor?
- [ ] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [ ] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by PaulTalbot-INL** [comment]
This issue currently isn't seen by the `Pyomo` dispatcher because it directly uses the transfer function rather than calling the `produce` method. This will help future dispatchers work as expected.
